"""add cancellation_review_status and carrier_penalty_due to bookings

Revision ID: 09e2544067d5
Revises: 848682a1b913
Create Date: 2026-05-21 10:22:21.949565

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '09e2544067d5'
down_revision: Union[str, None] = '848682a1b913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('cancellation_review_status', sa.String(length=20), nullable=True))
    op.add_column('bookings', sa.Column('carrier_penalty_due', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'carrier_penalty_due')
    op.drop_column('bookings', 'cancellation_review_status')
    # ### end Alembic commands ###
