"""add departure_time arrival_time to trips

Revision ID: 1472dcbf736e
Revises: b4c1aa522641
Create Date: 2026-04-30 16:35:39.788724

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1472dcbf736e'
down_revision: Union[str, None] = 'b4c1aa522641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('departure_time', sa.String(length=5), nullable=True))
    op.add_column('trips', sa.Column('arrival_time', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'arrival_time')
    op.drop_column('trips', 'departure_time')
    # ### end Alembic commands ###
