"""add_booking_financial_fields_v2

Revision ID: 2cd6312479dc
Revises: c51e227456eb
Create Date: 2026-05-09 00:07:45.512796

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2cd6312479dc'
down_revision: Union[str, None] = 'c51e227456eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('pickup_failed_by', sa.String(length=10), nullable=True))
    op.add_column('bookings', sa.Column('delivery_failed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('delivery_failed_comment', sa.String(length=500), nullable=True))
    op.add_column('bookings', sa.Column('delivery_failed_by', sa.String(length=10), nullable=True))
    op.add_column('bookings', sa.Column('incident_response_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('booking_fee_collected', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('bookings', sa.Column('cancellation_justified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'cancellation_justified')
    op.drop_column('bookings', 'booking_fee_collected')
    op.drop_column('bookings', 'incident_response_deadline')
    op.drop_column('bookings', 'delivery_failed_by')
    op.drop_column('bookings', 'delivery_failed_comment')
    op.drop_column('bookings', 'delivery_failed_at')
    op.drop_column('bookings', 'pickup_failed_by')
    # ### end Alembic commands ###
