"""add_pir_reports

Revision ID: 2e6da8fe960a
Revises: 42a14d29d0a1
Create Date: 2026-04-29 14:39:30.461087

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2e6da8fe960a'
down_revision: Union[str, None] = '42a14d29d0a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pir_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('carrier_id', sa.UUID(), nullable=False),
    sa.Column('pir_document_url', sa.String(length=500), nullable=True),
    sa.Column('airline_reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('found', sa.Boolean(), nullable=False),
    sa.Column('resolution_note', sa.String(length=500), nullable=True),
    sa.Column('affected_booking_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pir_reports_trip_id'), 'pir_reports', ['trip_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pir_reports_trip_id'), table_name='pir_reports')
    op.drop_table('pir_reports')
    # ### end Alembic commands ###
