"""add_username_address_to_users

Revision ID: 349dd5843a84
Revises: 76515cf6ca0b
Create Date: 2026-05-07 15:37:49.367099

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '349dd5843a84'
down_revision: Union[str, None] = '76515cf6ca0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('username_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=300), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'address')
    op.drop_column('users', 'username_updated_at')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
