"""add_reminder_hours_to_bookings

Revision ID: 406069cadfe6
Revises: 542e85b9028e
Create Date: 2026-05-13 19:35:36.823785

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '406069cadfe6'
down_revision: Union[str, None] = '542e85b9028e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('reminder_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'reminder_hours')
    # ### end Alembic commands ###
