"""add_2fa_fields_to_users

Revision ID: 45fab67a176d
Revises: 87b85cbbf8ca
Create Date: 2026-05-23 04:18:43.386741

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '45fab67a176d'
down_revision: Union[str, None] = '87b85cbbf8ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('totp_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('phone_2fa_enabled', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_2fa_enabled')
    op.drop_column('users', 'totp_verified')
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
