"""add_payout_fields_to_users

Revision ID: 512e1a99ddac
Revises: a1b2c3d4e5f7
Create Date: 2026-05-06 16:20:35.743700

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '512e1a99ddac'
down_revision: Union[str, None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('currency', sa.String(length=5), server_default='EUR', nullable=False))
    # Mettre a jour les NULL sur weight_unit avant NOT NULL
    op.execute("UPDATE users SET weight_unit = 'kg' WHERE weight_unit IS NULL")
    op.add_column('users', sa.Column('payment_method', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('payment_country', sa.String(length=5), nullable=True))
    op.add_column('users', sa.Column('mobile_money_number', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('iban', sa.String(length=50), nullable=True))
    op.alter_column('users', 'weight_unit',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'weight_unit',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.drop_column('users', 'iban')
    op.drop_column('users', 'mobile_money_number')
    op.drop_column('users', 'payment_country')
    op.drop_column('users', 'payment_method')
    op.drop_column('users', 'currency')
    # ### end Alembic commands ###
