"""add_pickup_code_fields_and_confirmations

Revision ID: 542e85b9028e
Revises: 65c48bd695cf
Create Date: 2026-05-11 22:56:42.276532

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '542e85b9028e'
down_revision: Union[str, None] = '65c48bd695cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('pickup_meeting_confirmed_by_sender', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('bookings', sa.Column('pickup_meeting_confirmed_by_carrier', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('bookings', sa.Column('pickup_code_hash', sa.String(length=200), nullable=True))
    op.add_column('bookings', sa.Column('pickup_code_plain', sa.String(length=10), nullable=True))
    op.add_column('bookings', sa.Column('pickup_qr_token', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('pickup_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('bookings', 'pickup_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('pickup_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('bookings', 'pickup_code_expires_at')
    op.drop_column('bookings', 'pickup_qr_token')
    op.drop_column('bookings', 'pickup_code_plain')
    op.drop_column('bookings', 'pickup_code_hash')
    op.drop_column('bookings', 'pickup_meeting_confirmed_by_carrier')
    op.drop_column('bookings', 'pickup_meeting_confirmed_by_sender')
    # ### end Alembic commands ###
