"""Add delivery scheduling and alternative proof fields

Revision ID: 65c48bd695cf
Revises: a194c462e1b8
Create Date: 2026-05-11 21:29:11.041835

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '65c48bd695cf'
down_revision: Union[str, None] = 'a194c462e1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('pickup_meeting_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('proposed_pickup_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('proposed_pickup_by', sa.UUID(), nullable=True))
    op.add_column('bookings', sa.Column('pickup_reschedule_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('bookings', sa.Column('pickup_code', sa.String(length=10), nullable=True))
    op.add_column('bookings', sa.Column('delivery_meeting_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('proposed_delivery_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('proposed_delivery_by', sa.UUID(), nullable=True))
    op.add_column('bookings', sa.Column('delivery_reschedule_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('bookings', sa.Column('delivery_alternative_proof_url', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'bookings', 'users', ['proposed_pickup_by'], ['id'])
    op.create_foreign_key(None, 'bookings', 'users', ['proposed_delivery_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'delivery_alternative_proof_url')
    op.drop_column('bookings', 'delivery_reschedule_count')
    op.drop_column('bookings', 'proposed_delivery_by')
    op.drop_column('bookings', 'proposed_delivery_date')
    op.drop_column('bookings', 'delivery_meeting_date')
    op.drop_column('bookings', 'pickup_code')
    op.drop_column('bookings', 'pickup_reschedule_count')
    op.drop_column('bookings', 'proposed_pickup_by')
    op.drop_column('bookings', 'proposed_pickup_date')
    op.drop_column('bookings', 'pickup_meeting_date')
    # ### end Alembic commands ###
