"""add_weight_unit_currency_to_trips_bookings

Revision ID: 662895be1867
Revises: d51d8aa8c4a3
Create Date: 2026-05-09 20:42:44.635536

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '662895be1867'
down_revision: Union[str, None] = 'd51d8aa8c4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('amount_local', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('weight_unit', sa.String(length=5), nullable=False, server_default=sa.text("'kg'")))
    op.add_column('bookings', sa.Column('currency', sa.String(length=5), nullable=False, server_default=sa.text("'EUR'")))
    op.add_column('trips', sa.Column('weight_unit', sa.String(length=5), nullable=False, server_default=sa.text("'kg'")))
    op.add_column('trips', sa.Column('currency', sa.String(length=5), nullable=False, server_default=sa.text("'EUR'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'currency')
    op.drop_column('trips', 'weight_unit')
    op.drop_column('bookings', 'currency')
    op.drop_column('bookings', 'weight_unit')
    op.drop_column('bookings', 'amount_local')
    # ### end Alembic commands ###
