"""add awaiting_receiver_reminded fields to bookings

Revision ID: 67ec9eb43dc5
Revises: 96fe7374e96b
Create Date: 2026-05-21 12:52:27.833512

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '67ec9eb43dc5'
down_revision: Union[str, None] = '96fe7374e96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('awaiting_receiver_reminded_24h', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('bookings', sa.Column('awaiting_receiver_reminded_36h', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'awaiting_receiver_reminded_36h')
    op.drop_column('bookings', 'awaiting_receiver_reminded_24h')
    # ### end Alembic commands ###
