"""add_language_to_user

Revision ID: 6a0cd0510730
Revises: 82edb3f93c06
Create Date: 2026-04-29 03:05:55.272239

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6a0cd0510730'
down_revision: Union[str, None] = '82edb3f93c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', sa.String(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    # ### end Alembic commands ###
