"""add deleted_at to bookings

Revision ID: 71a123171838
Revises: ade2961f91b0
Create Date: 2026-05-16 12:04:19.501377

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '71a123171838'
down_revision: Union[str, None] = 'ade2961f91b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'deleted_at')
    # ### end Alembic commands ###
