"""add_onboarding_completed_to_users

Revision ID: 76515cf6ca0b
Revises: a82fc56cf72f
Create Date: 2026-05-07 10:24:48.369019

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '76515cf6ca0b'
down_revision: Union[str, None] = 'a82fc56cf72f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    # ### end Alembic commands ###
