"""add accepts_urgent to trips and is_urgent booking_flat_fee_amount to bookings

Revision ID: 7d7904a4c15a
Revises: 67ec9eb43dc5
Create Date: 2026-05-21 13:16:21.538506

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7d7904a4c15a'
down_revision: Union[str, None] = '67ec9eb43dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('is_urgent', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('bookings', sa.Column('booking_flat_fee_amount', sa.Float(), nullable=False, server_default='1.5'))
    op.add_column('trips', sa.Column('accepts_urgent', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'accepts_urgent')
    op.drop_column('bookings', 'booking_flat_fee_amount')
    op.drop_column('bookings', 'is_urgent')
    # ### end Alembic commands ###
