"""add_receiver_invitations

Revision ID: 82edb3f93c06
Revises: 92ed9838f4e1
Create Date: 2026-04-29 02:17:51.131660

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '82edb3f93c06'
down_revision: Union[str, None] = '92ed9838f4e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receiver_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receiver_invitations_booking_id'), 'receiver_invitations', ['booking_id'], unique=False)
    op.create_index(op.f('ix_receiver_invitations_token'), 'receiver_invitations', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receiver_invitations_token'), table_name='receiver_invitations')
    op.drop_index(op.f('ix_receiver_invitations_booking_id'), table_name='receiver_invitations')
    op.drop_table('receiver_invitations')
    # ### end Alembic commands ###
