"""add premium fields to users and subscriptions table

Revision ID: 848682a1b913
Revises: 71a123171838
Create Date: 2026-05-16 21:40:49.860829

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '848682a1b913'
down_revision: Union[str, None] = '71a123171838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('payment_rail', sa.String(length=20), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=200), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=200), nullable=True),
    sa.Column('flw_transaction_id', sa.String(length=200), nullable=True),
    sa.Column('flw_subscription_id', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('premium_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('premium_plan', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('premium_stripe_sub_id', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('premium_flw_sub_id', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('kiparscan_monthly_uses', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('kiparscan_reset_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kiparscan_reset_at')
    op.drop_column('users', 'kiparscan_monthly_uses')
    op.drop_column('users', 'premium_flw_sub_id')
    op.drop_column('users', 'premium_stripe_sub_id')
    op.drop_column('users', 'premium_plan')
    op.drop_column('users', 'premium_expires_at')
    op.drop_column('users', 'is_premium')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
