"""add_mobile_money_provider_remove_flutterwave

Revision ID: 87b85cbbf8ca
Revises: 7d7904a4c15a
Create Date: 2026-05-22 00:07:59.904295

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '87b85cbbf8ca'
down_revision: Union[str, None] = '7d7904a4c15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile_money_provider', sa.String(length=50), nullable=True))
    op.drop_column('users', 'flutterwave_account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('flutterwave_account_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('users', 'mobile_money_provider')
    # ### end Alembic commands ###
