"""add package_request_id to bookings

Revision ID: 96fe7374e96b
Revises: dd00cee1565c
Create Date: 2026-05-21 11:54:23.483240

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '96fe7374e96b'
down_revision: Union[str, None] = 'dd00cee1565c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('package_request_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_bookings_package_request_id'), 'bookings', ['package_request_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'package_requests', ['package_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_package_request_id'), table_name='bookings')
    op.drop_column('bookings', 'package_request_id')
    # ### end Alembic commands ###
