"""Add arrival_date to Trip

Revision ID: a194c462e1b8
Revises: bb701b7060d9
Create Date: 2026-05-11 16:37:53.513426

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a194c462e1b8'
down_revision: Union[str, None] = 'bb701b7060d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('arrival_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'arrival_date')
    # ### end Alembic commands ###
