"""add_email_phone_verified_to_user

Revision ID: a5f940a81215
Revises: c8e93e0ee545
Create Date: 2026-05-04 01:35:22.406849

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a5f940a81215'
down_revision: Union[str, None] = 'c8e93e0ee545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
