"""add_notifications_and_soft_delete_to_user

Revision ID: aa5985aa1ff1
Revises: 1472dcbf736e
Create Date: 2026-05-02 01:18:40.610601

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'aa5985aa1ff1'
down_revision: Union[str, None] = '1472dcbf736e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('notify_by_email', sa.Boolean(), server_default=sa.true(), nullable=False)
    )
    op.add_column(
        'users',
        sa.Column('notify_by_push', sa.Boolean(), server_default=sa.true(), nullable=False)
    )
    op.add_column(
        'users',
        sa.Column('notify_by_sms', sa.Boolean(), server_default=sa.false(), nullable=False)
    )
    op.add_column(
        'users',
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'notify_by_sms')
    op.drop_column('users', 'notify_by_push')
    op.drop_column('users', 'notify_by_email')
    # ### end Alembic commands ###
