"""add_insurance_config

Revision ID: ade2961f91b0
Revises: f78bba8a9370
Create Date: 2026-05-13 20:38:40.380390

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ade2961f91b0'
down_revision: Union[str, None] = 'f78bba8a9370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_type', sa.String(length=10), nullable=False),
    sa.Column('rate_value', sa.Float(), nullable=False),
    sa.Column('min_premium', sa.Float(), nullable=False),
    sa.Column('max_coverage', sa.Float(), nullable=False),
    sa.Column('partner_name', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insurance_config')
    # ### end Alembic commands ###
