"""add_fcm_token_to_user

Revision ID: b603ec97fbfc
Revises: 6a0cd0510730
Create Date: 2026-04-29 04:10:00.433940

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b603ec97fbfc'
down_revision: Union[str, None] = '6a0cd0510730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fcm_token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fcm_token')
    # ### end Alembic commands ###
