"""Add pickup delivery meeting dates and codes

Revision ID: bb701b7060d9
Revises: e7d661e78cb5
Create Date: 2026-05-11 16:23:02.465535

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'bb701b7060d9'
down_revision: Union[str, None] = 'e7d661e78cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
