"""add_kyc_docs_to_users

Revision ID: c51e227456eb
Revises: 349dd5843a84
Create Date: 2026-05-08 00:14:17.916932

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c51e227456eb'
down_revision: Union[str, None] = '349dd5843a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kyc_id_front', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('kyc_id_back', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('kyc_selfie', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kyc_selfie')
    op.drop_column('users', 'kyc_id_back')
    op.drop_column('users', 'kyc_id_front')
    # ### end Alembic commands ###
