"""add_cgu_accepted_at_to_users

Revision ID: d51d8aa8c4a3
Revises: 2cd6312479dc
Create Date: 2026-05-09 19:28:03.089965

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd51d8aa8c4a3'
down_revision: Union[str, None] = '2cd6312479dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cgu_accepted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cgu_accepted_at')
    # ### end Alembic commands ###
