"""add_scan_credits

Revision ID: dc414adec9dd
Revises: 662895be1867
Create Date: 2026-05-09 21:26:49.949921

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'dc414adec9dd'
down_revision: Union[str, None] = '662895be1867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_credits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('free_credits_used', sa.Integer(), nullable=False),
    sa.Column('free_credits_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_credits', sa.Integer(), nullable=False),
    sa.Column('total_scans', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_credits_user_id'), 'scan_credits', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_credits_user_id'), table_name='scan_credits')
    op.drop_table('scan_credits')
    # ### end Alembic commands ###
