"""add cancellation_evidence_urls and cancellation_justification to bookings

Revision ID: dd00cee1565c
Revises: 09e2544067d5
Create Date: 2026-05-21 11:38:27.940502

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'dd00cee1565c'
down_revision: Union[str, None] = '09e2544067d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('cancellation_evidence_urls', sa.JSON(), nullable=True))
    op.add_column('bookings', sa.Column('cancellation_justification', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'cancellation_justification')
    op.drop_column('bookings', 'cancellation_evidence_urls')
    # ### end Alembic commands ###
