"""add_totp_backup_codes_table

Revision ID: e3874d347882
Revises: 45fab67a176d
Create Date: 2026-05-25 16:04:48.327205

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e3874d347882'
down_revision: Union[str, None] = '45fab67a176d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('totp_backup_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_totp_backup_codes_user_id'), 'totp_backup_codes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_totp_backup_codes_user_id'), table_name='totp_backup_codes')
    op.drop_table('totp_backup_codes')
    # ### end Alembic commands ###
