"""enrich_dispute_migrate_claims

Revision ID: e7d661e78cb5
Revises: dc414adec9dd
Create Date: 2026-05-09 23:06:07.114827

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e7d661e78cb5'
down_revision: Union[str, None] = 'dc414adec9dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disputes', sa.Column('initiated_by_role', sa.String(length=10), nullable=False, server_default=sa.text("'sender'")))
    op.add_column('disputes', sa.Column('incident_type', sa.String(length=30), nullable=False, server_default=sa.text("'other'")))
    op.add_column('disputes', sa.Column('incident_stage', sa.String(length=20), nullable=False, server_default=sa.text("'delivery'")))
    op.add_column('disputes', sa.Column('evidence_urls', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('disputes', sa.Column('respondent_comment', sa.Text(), nullable=True))
    op.add_column('disputes', sa.Column('respondent_evidence_urls', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('disputes', sa.Column('declared_value', sa.Float(), nullable=True))
    op.add_column('disputes', sa.Column('has_insurance', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('disputes', sa.Column('insurance_payout', sa.Float(), nullable=False, server_default=sa.text('0')))
    op.add_column('disputes', sa.Column('insurer_dossier_sent', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('disputes', sa.Column('insurer_dossier_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('disputes', sa.Column('insurer_reference', sa.String(length=200), nullable=True))
    op.add_column('disputes', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.add_column('disputes', sa.Column('conversation_id', sa.UUID(), nullable=True))
    # Migration Claims -> Disputes
    op.execute("""
        INSERT INTO disputes (id, booking_id, initiated_by, initiated_by_role, incident_type,
            incident_stage, reason, evidence_urls, respondent_evidence_urls,
            declared_value, has_insurance, insurance_payout, insurer_dossier_sent,
            status, resolution, created_at)
        SELECT gen_random_uuid(), c.booking_id, c.opened_by, 'sender', c.claim_type,
            'delivery', c.description, c.evidence_urls, '[]',
            NULL, false, c.insurance_payout, false,
            CASE c.status
                WHEN 'resolved_sender' THEN 'resolved_sender'
                WHEN 'resolved_carrier' THEN 'resolved_carrier'
                WHEN 'closed' THEN 'resolved_sender'
                ELSE 'open'
            END,
            c.resolution_note, c.opened_at
        FROM claims c
        WHERE NOT EXISTS (
            SELECT 1 FROM disputes d WHERE d.booking_id = c.booking_id
        )
    """)
    # Supprimer la table claims
    op.drop_table('claims')
    op.alter_column('disputes', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disputes', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('disputes', 'conversation_id')
    op.drop_column('disputes', 'admin_notes')
    op.drop_column('disputes', 'insurer_reference')
    op.drop_column('disputes', 'insurer_dossier_sent_at')
    op.drop_column('disputes', 'insurer_dossier_sent')
    op.drop_column('disputes', 'insurance_payout')
    op.drop_column('disputes', 'has_insurance')
    op.drop_column('disputes', 'declared_value')
    op.drop_column('disputes', 'respondent_evidence_urls')
    op.drop_column('disputes', 'respondent_comment')
    op.drop_column('disputes', 'evidence_urls')
    op.drop_column('disputes', 'incident_stage')
    op.drop_column('disputes', 'incident_type')
    op.drop_column('disputes', 'initiated_by_role')
    # ### end Alembic commands ###
