"""add_criteria_reviewer_role_to_reviews

Revision ID: eba02033b8c7
Revises: 512e1a99ddac
Create Date: 2026-05-06 17:42:29.694068

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'eba02033b8c7'
down_revision: Union[str, None] = '512e1a99ddac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reviews', sa.Column('reviewer_role', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'reviewer_role')
    op.drop_column('reviews', 'criteria')
    # ### end Alembic commands ###
