"""add_delivery_reminder_sent_to_bookings

Revision ID: f78bba8a9370
Revises: 406069cadfe6
Create Date: 2026-05-13 19:43:14.804579

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f78bba8a9370'
down_revision: Union[str, None] = '406069cadfe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('delivery_reminder_sent', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'delivery_reminder_sent')
    # ### end Alembic commands ###
