"""add_package_requests_and_applications

Revision ID: f86d35fdd822
Revises: f2b58aac8ccf
Create Date: 2026-05-03 05:04:23.280868

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f86d35fdd822'
down_revision: Union[str, None] = 'f2b58aac8ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('origin_city', sa.String(length=100), nullable=False),
    sa.Column('origin_airport_code', sa.String(length=3), nullable=False),
    sa.Column('destination_city', sa.String(length=100), nullable=False),
    sa.Column('destination_airport_code', sa.String(length=3), nullable=False),
    sa.Column('content_description', sa.Text(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('declared_value', sa.Float(), nullable=True),
    sa.Column('budget_per_kg', sa.Float(), nullable=False),
    sa.Column('photos', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('receiver_email_or_phone', sa.String(length=200), nullable=False),
    sa.Column('deadline_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_requests_deadline_date'), 'package_requests', ['deadline_date'], unique=False)
    op.create_index(op.f('ix_package_requests_destination_airport_code'), 'package_requests', ['destination_airport_code'], unique=False)
    op.create_index(op.f('ix_package_requests_origin_airport_code'), 'package_requests', ['origin_airport_code'], unique=False)
    op.create_index(op.f('ix_package_requests_sender_id'), 'package_requests', ['sender_id'], unique=False)
    op.create_index(op.f('ix_package_requests_status'), 'package_requests', ['status'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_request_id', sa.UUID(), nullable=False),
    sa.Column('carrier_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['package_request_id'], ['package_requests.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_carrier_id'), 'applications', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_applications_package_request_id'), 'applications', ['package_request_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_trip_id'), 'applications', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_trip_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_package_request_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_carrier_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_package_requests_status'), table_name='package_requests')
    op.drop_index(op.f('ix_package_requests_sender_id'), table_name='package_requests')
    op.drop_index(op.f('ix_package_requests_origin_airport_code'), table_name='package_requests')
    op.drop_index(op.f('ix_package_requests_destination_airport_code'), table_name='package_requests')
    op.drop_index(op.f('ix_package_requests_deadline_date'), table_name='package_requests')
    op.drop_table('package_requests')
    # ### end Alembic commands ###
