"""add_cancellation_reason_to_bookings

Revision ID: fb4c3385d3c4
Revises: c3d4e5f6a7b8
Create Date: 2026-05-05 12:04:25.148150

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fb4c3385d3c4'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('cancellation_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'cancellation_reason')
    # ### end Alembic commands ###
